# Google Ads account ID; digits only, no dashes
client_customer_id: 
# OAuth2 credentials for Installed App.
client_id:
client_secret: 
# Google Ads developer token.
# Refer to [Apply for access to the AdWords API](https://developers.google.com/adwords/api/docs/guides/signup#step-2).
developer_token:
refresh_token: 